[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  # Function timeout in seconds (max 10 for free tier)
  timeout = 10

[dev]
  # Local development settings
  functions = "netlify/functions"
  port = 8888

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect all unknown paths to 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Environment variable examples (set these in Netlify UI)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development" 