[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  # Functions directory configuration
  # Timeout defaults to 10 seconds on free tier

[dev]
  # Local development settings
  functions = "netlify/functions"
  port = 8888

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect all unknown paths to index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable examples (set these in Netlify UI)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development" 